name: kawaiflow
description: A fluid simulation app for anxiety relief.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  go_router: ^16.3.0
  google_fonts: ^6.3.2
  provider: ^6.1.5+1
  shader_buffers: ^1.1.2
  vector_math: ^2.1.4
  flame: ^1.33.0
  flame_forge2d: ^0.19.2+1
  firebase_core: ^4.2.0
  firebase_ai: ^3.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/kawaiflowPixelPro-ANDROID-Icons/icon-Play-Store-512x512.png"

flutter:
  uses-material-design: true

  assets:
    - assets/shaders/
    - assets/kawaiflowPixelPro-ANDROID-Icons/
